import { AlertProvider } from './context/AlertContext'
import './globals.css'


export const metadata = {
  title: 'Finance Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <AlertProvider>
        {children}
        </AlertProvider>
        </body>
    </html>
  )
}
